apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: love-coordinator
  template:
    metadata:
      labels:
        app: love-coordinator
    spec:
      containers:
      - name: coordinator-container
        image: tu_nombre_de_usuario/love-coordinator:latest
        env:
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: RABBITMQ_HOST